//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SabaMediaLock.Locker.SiteServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SiteServiceReference.ISiteService")]
    public interface ISiteService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiteService/CanLogin", ReplyAction="http://tempuri.org/ISiteService/CanLoginResponse")]
        bool CanLogin(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiteService/IsSoftwareUniqueNameValid", ReplyAction="http://tempuri.org/ISiteService/IsSoftwareUniqueNameValidResponse")]
        bool IsSoftwareUniqueNameValid(string username, string password, string uniqueName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISiteServiceChannel : SabaMediaLock.Locker.SiteServiceReference.ISiteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SiteServiceClient : System.ServiceModel.ClientBase<SabaMediaLock.Locker.SiteServiceReference.ISiteService>, SabaMediaLock.Locker.SiteServiceReference.ISiteService {
        
        public SiteServiceClient() {
        }
        
        public SiteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SiteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SiteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SiteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CanLogin(string username, string password) {
            return base.Channel.CanLogin(username, password);
        }
        
        public bool IsSoftwareUniqueNameValid(string username, string password, string uniqueName) {
            return base.Channel.IsSoftwareUniqueNameValid(username, password, uniqueName);
        }
    }
}
