// <auto-generated />
namespace SabaSoftwareLock.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Mig5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Mig5));
        
        string IMigrationMetadata.Id
        {
            get { return "201209100917025_Mig5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
