// <auto-generated />
namespace SabaSoftwareLock.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Mig6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Mig6));
        
        string IMigrationMetadata.Id
        {
            get { return "201209100922515_Mig6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
