<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Members.aspx.cs" Inherits="SabaSoftwareLock.Web.Admin.Members" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <telerik:RadAjaxPanel ID="RadAjaxPanel1" runat="server" LoadingPanelID="RadAjaxLoadingPanel1" >
    <telerik:RadGrid ID="RadGrid1" runat="server" AllowFilteringByColumn="True" style="direction:ltr"
        AllowPaging="True" AllowSorting="True" CellSpacing="0" GridLines="None" 
        ShowGroupPanel="True" PageSize="50" DataSourceID="SqlDataSource1" 
        AllowAutomaticDeletes="True" AllowAutomaticInserts="True" 
        AllowAutomaticUpdates="True" AutoGenerateDeleteColumn="True" 
        AutoGenerateEditColumn="True" OnInsertCommand="RadGrid1_InsertCommand" 
            OnItemCommand="RadGrid1_ItemCommand">
        <ClientSettings AllowColumnsReorder="True" AllowDragToGroup="True" 
            ReorderColumnsOnClient="True">
        </ClientSettings>
<MasterTableView DataSourceID="SqlDataSource1" AutoGenerateColumns="False" 
            DataKeyNames="MemberId" CommandItemDisplay="TopAndBottom" TableLayout="Fixed">
<CommandItemSettings ExportToPdfText="Export to PDF"></CommandItemSettings>

<RowIndicatorColumn Visible="True" FilterControlAltText="Filter RowIndicator column">
<HeaderStyle Width="20px"></HeaderStyle>
</RowIndicatorColumn>

<ExpandCollapseColumn Visible="True" FilterControlAltText="Filter ExpandColumn column">
<HeaderStyle Width="20px"></HeaderStyle>
</ExpandCollapseColumn>

    <Columns>
        <telerik:GridBoundColumn DataField="MemberId" DataType="System.Int32" 
            FilterControlAltText="Filter MemberId column" HeaderText="MemberId" 
            ReadOnly="True" SortExpression="MemberId" UniqueName="MemberId">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="FirstName" 
            FilterControlAltText="Filter FirstName column" HeaderText="FirstName" 
            SortExpression="FirstName" UniqueName="FirstName">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="LastName" 
            FilterControlAltText="Filter LastName column" HeaderText="LastName" 
            SortExpression="LastName" UniqueName="LastName">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="UserName" 
            FilterControlAltText="Filter UserName column" HeaderText="UserName" 
            SortExpression="UserName" UniqueName="UserName">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="Password" 
            FilterControlAltText="Filter Password column" HeaderStyle-Width="100px" ItemStyle-Width="100px" HeaderText="Password" 
            SortExpression="Password" UniqueName="Password">
             <HeaderStyle Width="150px" /> 
             <ItemStyle Width="150px" />
        </telerik:GridBoundColumn>
        <telerik:GridCheckBoxColumn DataField="IsOnline" DataType="System.Boolean" 
            FilterControlAltText="Filter IsOnline column" HeaderText="IsOnline" 
            SortExpression="IsOnline" UniqueName="IsOnline">
        </telerik:GridCheckBoxColumn>
        <telerik:GridBoundColumn DataField="Role" 
            FilterControlAltText="Filter Role column" HeaderText="Role" 
            SortExpression="Role" UniqueName="Role">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="Charge" DataType="System.Decimal" 
            FilterControlAltText="Filter Charge column" HeaderText="Charge" 
            SortExpression="Charge" UniqueName="Charge">
            <ItemStyle Width="100px" />
        </telerik:GridBoundColumn>
    </Columns>

<EditFormSettings>
<EditColumn FilterControlAltText="Filter EditCommandColumn column"></EditColumn>
</EditFormSettings>
    <PagerStyle AlwaysVisible="True" />
</MasterTableView>

        <HeaderStyle Wrap="True" />

        <PagerStyle AlwaysVisible="True" />

<FilterMenu EnableImageSprites="False">
<WebServiceSettings>
<ODataSettings InitialContainerName=""></ODataSettings>
</WebServiceSettings>
</FilterMenu>

<HeaderContextMenu CssClass="GridContextMenu GridContextMenu_Default">
<WebServiceSettings>
<ODataSettings InitialContainerName=""></ODataSettings>
</WebServiceSettings>
</HeaderContextMenu>
    </telerik:RadGrid>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:LockWebDbContext %>" 
        
        SelectCommand="SELECT * FROM [Members]" 
        DeleteCommand="DELETE FROM [Members] WHERE [MemberId] = @MemberId" 
        InsertCommand="INSERT INTO [Members] ([FirstName], [LastName], [UserName], [Password], [IsOnline], [Role], [Charge]) VALUES (@FirstName, @LastName, @UserName, @Password, @IsOnline, @Role, @Charge)" 
        
        
        UpdateCommand="UPDATE [Members] SET [FirstName] = @FirstName, [LastName] = @LastName, [UserName] = @UserName, [Password] = @Password, [IsOnline] = @IsOnline, [Role] = @Role, [Charge] = @Charge WHERE [MemberId] = @MemberId">
        <DeleteParameters>
            <asp:Parameter Name="MemberId" Type="Int32" />
        </DeleteParameters>
        <InsertParameters>
            <asp:Parameter Name="FirstName" Type="String" />
            <asp:Parameter Name="LastName" Type="String" />
            <asp:Parameter Name="UserName" Type="String" />
            <asp:Parameter Name="Password" Type="String" />
            <asp:Parameter Name="IsOnline" Type="Boolean" />
            <asp:Parameter Name="Role" Type="String" />
            <asp:Parameter Name="Charge" Type="Decimal" />
        </InsertParameters>
        <UpdateParameters>
            <asp:Parameter Name="FirstName" Type="String" />
            <asp:Parameter Name="LastName" Type="String" />
            <asp:Parameter Name="UserName" Type="String" />
            <asp:Parameter Name="Password" Type="String" />
            <asp:Parameter Name="IsOnline" Type="Boolean" />
            <asp:Parameter Name="Role" Type="String" />
            <asp:Parameter Name="Charge" Type="Decimal" />
            <asp:Parameter Name="MemberId" Type="Int32" />
        </UpdateParameters>
    </asp:SqlDataSource>
        <asp:Panel ID="Panel1" runat="server">
            <asp:TextBox ID="txtSmplPass" runat="server" placeholder="password..."></asp:TextBox>
            <asp:Button ID="btnEncrypt" runat="server" Text="Hash It !" 
                OnClick="btnEncrypt_Click" />
            <asp:TextBox ID="txtEncPass" runat="server" Text="" Width="200px"></asp:TextBox>
        </asp:Panel>
        </telerik:RadAjaxPanel> 
    <telerik:RadAjaxLoadingPanel ID="RadAjaxLoadingPanel1" runat="server" Skin="Default">
    </telerik:RadAjaxLoadingPanel>
</asp:Content>
