//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareSerial.Client.SerialServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserSerialValidationResult", Namespace="http://schemas.datacontract.org/2004/07/SoftwareSerial.Model")]
    public enum UserSerialValidationResult : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IsValid = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IsUsedMoreThan = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PackageSerialIsNotInDb = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HardwareSerialNotMatches = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SoftwareNameNotMatchesPackageSerial = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.sabapardaz.com/services/ISerialService", ConfigurationName="SerialServiceReference.ISerialService")]
    public interface ISerialService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sabapardaz.com/services/ISerialService/ISerialService/Validate", ReplyAction="http://www.sabapardaz.com/services/ISerialService/ISerialService/ValidateResponse" +
            "")]
        SoftwareSerial.Contracts.SerialValidationContract Validate(string softwareName, string packageSerial, string automatedHardwareSerial);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISerialServiceChannel : SoftwareSerial.Client.SerialServiceReference.ISerialService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SerialServiceClient : System.ServiceModel.ClientBase<SoftwareSerial.Client.SerialServiceReference.ISerialService>, SoftwareSerial.Client.SerialServiceReference.ISerialService {
        
        public SerialServiceClient() {
        }
        
        public SerialServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SerialServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SerialServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SerialServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SoftwareSerial.Contracts.SerialValidationContract Validate(string softwareName, string packageSerial, string automatedHardwareSerial) {
            return base.Channel.Validate(softwareName, packageSerial, automatedHardwareSerial);
        }
    }
}
